[package]
name = "jsonrpc-derive"
version = "0.1.0"
authors = [
    "Eric Förster <eric.foerster@outlook.com>", 
    "Patrick Förster <patrick.foerster@outlook.de>"]
edition = "2018"

[lib]
proc-macro = true
doctest = false

[dependencies]
syn = "1.0"
quote = "1.0"
