[package]
name = "texlab-reference"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
futures = "0.3"
futures-boxed = { path = "../futures_boxed" }
log = "0.4"
petgraph = { version = "0.5", features = ["serde-1"] }
texlab-feature = { path = "../texlab_feature" }
texlab-protocol = { path = "../texlab_protocol" }
texlab-syntax = { path = "../texlab_syntax" }
texlab-tex = { path = "../texlab_tex" }
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
indoc = "0.3"
