trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*
jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - template: .build-steps.yml
        parameters:
          executableName: "texlab"
          archiveFile: "texlab-x86_64-linux.tar.gz"
          archiveType: "tar"
          linux: true
  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: .build-steps.yml
        parameters:
          executableName: "texlab.exe"
          archiveFile: "texlab-x86_64-windows.zip"
          archiveType: "zip"
  - job: macOS
    pool:
      vmImage: "macos-10.14"
    steps:
      - bash: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain none
          echo "##vso[task.prependpath]$HOME/.cargo/bin"
        displayName: "Install rustup"
      - template: .build-steps.yml
        parameters:
          executableName: "texlab"
          archiveFile: "texlab-x86_64-macos.tar.gz"
          archiveType: "tar"
  - job: Publish
    pool:
      vmImage: "ubuntu-16.04"
    dependsOn:
      - Linux
      - Windows
      - macOS
    condition: |
      and(
        contains(variables['Build.SourceBranch'], 'tags'),
        succeeded('Linux'), 
        succeeded('Windows'), 
        succeeded('macOS'))
    steps:
      - download: current
        patterns: "**/texlab*"
      - bash: |
          ver=`echo "$(Build.SourceBranchName)" | cut -c2-`
          echo "##vso[task.setvariable variable=version]$ver"
        displayName: "Set version variable"
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: "$(aurKnownHosts)"
          sshPublicKey: "$(aurPubKey)"
          sshKeySecureFile: "aur"
        displayName: "Use AUR SSH key"
      - bash: |
          git clone ssh://aur@aur.archlinux.org/texlab.git
          cd texlab
          wget https://github.com/latex-lsp/texlab/archive/$(Build.SourceBranchName).tar.gz
          checksum=`sha512sum $(Build.SourceBranchName).tar.gz | cut -d " " -f 1`
          sed -i -E -e "s/[0-9]+\.[0-9]+\.[0-9]+/$(version)/" \
                    -e "s/(pkgrel\s*=\s*)[0-9]+/\11/" \
                    -e "s/[0-9a-fA-F]{128}/$checksum/" PKGBUILD .SRCINFO
          git config --global user.name "Eric Förster"
          git config --global user.email "eric.foerster@outlook.com"
          git commit -am "Update to upstream version $(version)"
          git push
        displayName: "Update AUR package"
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: latex-lsp
          repositoryName: latex-lsp/texlab
          assets: "$(Pipeline.Workspace)/**/texlab*"
        displayName: "Create GitHub release"
