trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*
jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - template: .build-steps.yml
        parameters:
          executableName: "texlab"
          archiveFile: "texlab-x86_64-linux.tar.gz"
          archiveType: "tar"
          coverage: true
  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: .build-steps.yml
        parameters:
          executableName: "texlab.exe"
          archiveFile: "texlab-x86_64-windows.zip"
          archiveType: "zip"
  - job: macOS
    pool:
      vmImage: "macos-10.14"
    steps:
      - bash: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain none
          echo "##vso[task.prependpath]$HOME/.cargo/bin"
        displayName: "Install rustup"
      - template: .build-steps.yml
        parameters:
          executableName: "texlab"
          archiveFile: "texlab-x86_64-macos.tar.gz"
          archiveType: "tar"
  - job: Publish
    pool:
      vmImage: "ubuntu-16.04"
    dependsOn:
      - Linux
      - Windows
      - macOS
    condition: |
      and(
        contains(variables['Build.SourceBranch'], 'tags'),
        succeeded('Linux'), 
        succeeded('Windows'), 
        succeeded('macOS'))
    steps:
      - download: current
        patterns: "**/texlab*"
      - bash: |
          ver=`echo "$(Build.SourceBranchName)" | cut -c2-`
          echo "##vso[task.setvariable variable=version]$ver"
        displayName: "Set version variable"
      - bash: |
          curl -T $(Pipeline.Workspace)/texlab-x86_64-debian.deb/*.deb \
               -uefoerster:$BINTRAY_API_KEY \
               https://api.bintray.com/content/efoerster/texlab-deb/texlab/$version/texlab-x86_64-debian.deb;deb_distribution=stable;deb_component=main;deb_architecture=amd64
          curl -T $(Pipeline.Workspace)/texlab-x86_64-rhel.rpm/*.rpm \
               -uefoerster:$BINTRAY_API_KEY \
               https://api.bintray.com/content/efoerster/texlab-rpm/texlab/$version/texlab-x86_64-rhel.rpm
        env:
          BINTRAY_API_KEY: $(bintrayKey)
        displayName: "Upload to Bintray"
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: latex-lsp
          repositoryName: latex-lsp/texlab
          assets: "$(Pipeline.Workspace)/**/texlab*"
        displayName: "Create GitHub release"
