trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*
pool:
  vmImage: 'ubuntu-16.04'
steps:
- task: Gradle@2
  inputs:
    tasks: 'build jacocoTestReport'
    jdkVersionOption: '1.8'
    publishJUnitResults: true
    testResultsFiles: '**/jacocoTestReport.xml'
    codeCoverageToolOption: 'jaCoCo'
  displayName: 'Build and Test'
- task: GitHubRelease@0
  inputs:
    gitHubConnection: latex-lsp
    repositoryName: latex-lsp/texlab
    assets: build/libs/texlab.jar
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
  displayName: 'Publish to GitHub'
