trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*
variables:
  isReleaseBuild: $[contains(variables['Build.SourceBranch'], 'tags')]
jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - template: .build-steps.yml
        parameters:
          target: "x86_64-unknown-linux-gnu"
          executableName: "texlab"
          archiveFile: "texlab-x86_64-linux.tar.gz"
          archiveType: "tar"
          coverage: true
  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: .build-steps.yml
        parameters:
          target: "x86_64-pc-windows-msvc"
          executableName: "texlab.exe"
          archiveFile: "texlab-x86_64-windows.zip"
          archiveType: "zip"
  - job: macOS
    pool:
      vmImage: "macos-10.14"
    steps:
      - bash: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain none
          echo "##vso[task.prependpath]$HOME/.cargo/bin"
        displayName: "Install rustup"
      - template: .build-steps.yml
        parameters:
          target: "x86_64-apple-darwin"
          executableName: "texlab"
          archiveFile: "texlab-x86_64-macos.tar.gz"
          archiveType: "tar"
  - job: Publish
    dependsOn:
      - Linux
      - Windows
      - macOS
    condition: |
      and(
        eq(variables['isReleaseBuild'], 'true'),
        succeeded('Linux'), 
        succeeded('Windows'), 
        succeeded('macOS'))
    steps:
      - download: current
        patterns: "**/texlab*"
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: latex-lsp
          repositoryName: latex-lsp/texlab
          assets: "$(Pipeline.Workspace)/**/texlab*"
        displayName: "Create GitHub release"
