parameters:
  target: ""
  executableName: ""
  artifactName: ""

steps:
  - bash: |
      cd citeproc
      yarn
      yarn dist
      cd ..
      cargo test --all
    displayName: "Run tests"
  - bash: |
      cargo build --release --target ${{ parameters.target }}
      cp target/${{ parameters.target }}/${{ parameters.executableName }} $(Build.ArtifactStagingDirectory)/${{ parameters.artifactName }}
    condition: and(succeeded(), eq(variables['isReleaseBuild'], 'true'))
    displayName: "Build release artifact"
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: ${{ parameters.artifactName }}
    condition: and(succeeded(), eq(variables['isReleaseBuild'], 'true'))
