language: java
jdk:
  - openjdk8
  - openjdk11
env:
  - CODECOV_TOKEN="5afa517f-cf99-47b4-bd24-76c3ab45fd74"
before_install:
  - chmod +x ./gradlew
  - chmod +x ./gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew test
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
