[package]
name = "texlab"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
lsp-types = "0.56.0"
