[package]
name = "texlab"
description = "LaTeX Language Server"
version = "2.0.0"
license = "GPLv3"
readme = "README.md"
authors = [
    "Eric Förster <eric.foerster@outlook.com>", 
    "Patrick Förster <patrick.foerster@outlook.de>"]
edition = "2018"

[workspace]
members = ["crates/*"]

[lib]
doctest = false

[dependencies]
async-trait = "0.1"
aovec = "1.1"
base64 = "0.12"
bibutils-sys = { path = "crates/bibutils_sys" }
byteorder = "1.3"
bytes = "0.5"
chashmap = "2.2"
citeproc = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221" }
citeproc-db = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221" }
citeproc-io = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221" }
csl = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221" }
clap = "2.33"
fern = "0.6"
fnv = "1.0"
futures = "0.3"
html2md = "0.2"
image = "0.23"
itertools = "0.9"
jsonrpc = { path = "crates/jsonrpc" }
jsonrpc-derive = { path = "crates/jsonrpc_derive" }
lalrpop-util = "0.18"
log = "0.4"
lsp-types = "0.74.0"
nom = "5.1"
once_cell = "1.3"
petgraph = { version = "0.5", features = ["serde-1"] }
rayon = "1.3"
regex = "1.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1"
tempfile = "3.1"
thiserror = "1.0"
titlecase = "1.1"
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3", features = ["codec"] }
url = "2.1"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
criterion = "0.3"
indoc = "0.3"

[build-dependencies]
lalrpop = { version = "0.18", features = ["lexer"] }

[profile.bench]
lto = false

[profile.release]
lto = true

[[bench]]
name = "bench_main"
harness = false
