[package]
name = "texlab"
description = "LaTeX Language Server"
version = "2.2.2"
license = "GPL-3.0"
readme = "README.md"
authors = [
    "Eric Förster <eric.foerster@outlook.com>",
    "Patrick Förster <patrick.foerster@outlook.de>",
]
edition = "2018"
homepage = "https://texlab.netlify.app"

[lib]
doctest = false

[features]

[dependencies]
logos = "0.12.0"
lsp-types = "0.88.0"
rowan = "0.12.6"
salsa = "0.16.0"
smol_str = "0.1.17"

[dev-dependencies]
criterion = "0.3.4"

[build-dependencies]

[profile.release]
lto = true

[[bench]]
name = "bench_main"
harness = false