[package]
name = "texlab"
description = "LaTeX Language Server"
version = "2.2.2"
license = "GPL-3.0"
readme = "README.md"
authors = [
    "Eric Förster <eric.foerster@outlook.com>",
    "Patrick Förster <patrick.foerster@outlook.de>",
]
edition = "2018"
homepage = "https://texlab.netlify.app"

[lib]
doctest = false

[features]

[dependencies]
anyhow = "1.0.40"
byteorder = "1.4.3"
cstree = "0.3.0"
derive_more = "0.99.13"
lasso = "0.5.0"
log = "0.4.14"
logos = "0.12.0"
lsp-types = "0.88.0"
rayon = "1.5.0"
ra_ap_text_edit = "0.0.44"
rustc-hash = "1.1.0"
salsa = "0.16.0"
serde = "1.0.125"
serde_json = "1.0.64"
serde_repr = "0.1.6"
smol_str = "0.1.17"
thiserror = "1.0.24"
url = "2.2.1"
variantly = "0.2.0"

[dev-dependencies]
criterion = "0.3.4"
insta = "1.7.1"

[build-dependencies]

[profile.release]
lto = true

[[bench]]
name = "bench_main"
harness = false