[workspace]
members = ["lib/*", "crates/*"]
resolver = "2"

[profile.dev.package]
# TODO: Enable optimized builds for a selected set of crates for faster tests

# Uncomment this once we bump the MSRV to Rust 1.57:
#
# [profile.production]
# inherits = "release"
# lto = true
# codegen-units = 1
