[package]
name = "texlab"
description = "LaTeX Language Server"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
lsp-types = "0.56.0"
futures-preview = { version = "0.3.0-alpha.14", features = ["compat"] }
jsonrpc-core = "11.0.0"
jsonrpc-core-client = "11.0.0"
serde_json = "1.0.39"
tokio = "0.1"
tokio-stdin-stdout = "0.1"
tokio-codec = "0.1"
bytes = "0.4.12"
nom = "4.2.3"
log = "0.4.6"
stderrlog = "0.4.1"
clap = "2.33"
indoc = "0.3.1"
regex = "1.1.6"
url = "1.7.2"
path-clean = "0.1.0"
