[package]
name = "texlab"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
lsp-types = "0.56.0"
futures = "0.1.26"
jsonrpc-core = "11.0.0"
jsonrpc-core-client = "11.0.0"
serde_json = "1.0.39"
tokio = "0.1"
tokio-stdin-stdout = "0.1"
tokio-codec = "0.1"
