[workspace]
members = ["lib/*", "crates/*"]
resolver = "2"

[profile.dev.package]
# TODO: Enable optimized builds for a selected set of crates for faster tests

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
