[package]
name = "texlab"
description = "LaTeX Language Server"
version = "1.10.0"
license = "GPLv3"
readme = "README.md"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = [
    "crates/bibutils_sys",
    "crates/futures_boxed",
    "crates/jsonrpc_derive"
]

[lib]
doctest = false

[dependencies]
aovec = "1.1"
base64 = "0.12"
bibutils-sys = { path = "crates/bibutils_sys" }
byteorder = "1.3"
bytes = "0.5"
citeproc = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221" }
citeproc-db = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221" }
citeproc-io = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221" }
chashmap = "2.2"
clap = "2.33"
csl = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221" }
fnv = "1.0"
futures = "0.3"
futures-boxed = { path = "crates/futures_boxed" }
html2md = "0.2"
image = "0.23"
itertools = "0.8"
jsonrpc-derive = { path = "crates/jsonrpc_derive" }
lalrpop-util = "0.18"
log = "0.4"
lsp-types = "0.73.0"
nom = "5.1"
once_cell = "1.3"
petgraph = { version = "0.5", features = ["serde-1"] }
rayon = "1.3"
regex = "1.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1"
stderrlog = "0.4"
tempfile = "3.1"
thiserror = "1.0"
titlecase = "1.1"
tokio = { version = "0.2", features = ["blocking", "fs", "io-std", "io-util", "macros", "process", "stream", "time"] }
tokio-util = { version = "0.2", features = ["codec"] }
url = "2.1"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
criterion = "0.3"
indoc = "0.3"

[build-dependencies]
lalrpop = { version = "0.18", features = ["lexer"] }

[profile.release]
lto = true

[[bench]]
name = "bench_main"
harness = false
