[package]
name = "texlab"
description = "LaTeX Language Server"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = ["./jsonrpc", "./jsonrpc_derive"]

[dependencies]
bytes = "0.4.12"
clap = "2.33"
copy_dir = "0.1.2"
futures-boxed = { path = "futures_boxed" }
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
html2md = "0.2.9"
indoc = "0.3.1"
itertools = "0.8.0"
jsonrpc = { path = "jsonrpc" }
jsonrpc-derive = { path = "jsonrpc_derive" }
lazy_static = "1.3.0"
log = "0.4.6"
lsp-types = { git = "https://github.com/latex-lsp/lsp-types", rev = "eb34c6ebd1e327946e62a9bbc3835a850fd260b3", features = ["proposed"] }
nom = "5.0.0-beta2"
path-clean = "0.1.0"
regex = "1.1.6"
reqwest = "0.9.16"
serde = { version = "1.0.90", features = ["derive", "rc"] }
serde_json = "1.0.39"
serde_repr = "0.1"
stderrlog = "0.4.1"
tempfile = "3"
tokio = "0.1"
tokio-codec = "0.1"
tokio-stdin-stdout = "0.1"
url = "1.7.2"
url_serde = "0.2.0"
walkdir = "2"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "completion"
harness = false

[profile.release]
lto = true