[package]
name = "texlab"
description = "LaTeX Language Server"
version = "1.10.0"
license = "GPLv3"
readme = "README.md"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = [
    "crates/futures_boxed",
    "crates/jsonrpc_derive"
]

[dependencies]
byteorder = "1.3"
bytes = "0.5"
chashmap = "2.2"
clap = "2.33"
futures = "0.3"
futures-boxed = { path = "crates/futures_boxed" }
itertools = "0.8"
jsonrpc-derive = { path = "crates/jsonrpc_derive" }
log = "0.4"
lsp-types = { version = "0.61.0", features = ["proposed"] }
nom = "5.1"
once_cell = "1.3"
petgraph = { version = "0.5", features = ["serde-1"] }
rayon = "1.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1"
stderrlog = "0.4"
tempfile = "3.1"
tokio = { version = "0.2", features = ["fs", "io-std", "macros", "process", "time"] }
tokio-util = { version = "0.2", features = ["codec"] }
url = "2.1"

[dev-dependencies]
criterion = "0.3"
indoc = "0.3"

[profile.release]
lto = true

[[bench]]
name = "bench_main"
harness = false
