[package]
name = "texlab"
description = "LaTeX Language Server"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = ["./jsonrpc", "./jsonrpc_derive"]

[dependencies]
jsonrpc = { path = "jsonrpc" }
jsonrpc-derive = { path = "jsonrpc_derive" }
lsp-types = { git = "https://github.com/latex-lsp/lsp-types", rev = "8ce88a90c6753cf10d4b97d8cd6c9b8bb663c9d1" }
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
serde = { version = "1.0.90", features = ["derive", "rc"] }
serde_json = "1.0.39"
tokio = "0.1"
tokio-stdin-stdout = "0.1"
tokio-codec = "0.1"
bytes = "0.4.12"
nom = "4.2.3"
log = "0.4.6"
stderrlog = "0.4.1"
clap = "2.33"
indoc = "0.3.1"
regex = "1.1.6"
url = "1.7.2"
url_serde = "0.2.0"
path-clean = "0.1.0"
itertools = "0.8.0"
walkdir = "2"
