[package]
name = "texlab"
description = "LaTeX Language Server"
version = "1.10.0"
license = "GPLv3"
readme = "README.md"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = ["crates/*"]

[lib]
doctest = false

[dependencies]
aovec = "1.1"
base64 = "0.12"
chashmap = "2.2"
clap = "2.33"
futures = "0.3"
futures-boxed = { path = "crates/futures_boxed" }
html2md = "0.2"
image = "0.23"
itertools = "0.8"
jsonrpc = { path = "crates/jsonrpc" }
jsonrpc-derive = { path = "crates/jsonrpc_derive" }
log = "0.4"
once_cell = "1.3"
petgraph = { version = "0.5", features = ["serde-1"] }
regex = "1.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1"
stderrlog = "0.4"
tempfile = "3.1"
texlab-citeproc = { path = "crates/texlab_citeproc" }
texlab-components = { path = "crates/texlab_components" }
texlab-protocol = { path = "crates/texlab_protocol" }
texlab-syntax = { path = "crates/texlab_syntax" }
texlab-tex = { path = "crates/texlab_tex" }
thiserror = "1.0"
titlecase = "1.1"
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"] }
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
criterion = "0.3"
indoc = "0.3"

[profile.release]
lto = true

[[bench]]
name = "bench_main"
harness = false
