[package]
name = "texlab"
description = "LaTeX Language Server"
version = "2.2.2"
license = "GPL-3.0"
readme = "README.md"
authors = [
    "Eric Förster <eric.foerster@outlook.com>",
    "Patrick Förster <patrick.foerster@outlook.de>",
]
edition = "2018"
homepage = "https://texlab.netlify.app"

[lib]
doctest = false

[features]

[dependencies]
anyhow = "1.0.40"
byteorder = "1.4.3"
cancellation = "0.1"
crossbeam-channel = "0.5.1"
cstree = "0.4.0"
derive_more = "0.99.13"
fern = "0.6"
log = "0.4.14"
logos = "0.12.0"
lsp-server = "0.5"
lsp-types = "0.89.0"
notify = "5.0.0-pre.7"
once_cell = "1.7.2"
petgraph = "0.5.1"
rayon = "1.5.0"
ra_ap_text_edit = "0.0.44"
rustc-hash = "1.1.0"
serde = "1.0.125"
serde_json = "1.0.64"
smol_str = { version = "0.1.17", features = ["serde"] }
structopt = "0.3"
threadpool = "1.8.1"
url = "2.2.1"
variantly = "0.2.0"

[dev-dependencies]
insta = "1.7.1"

[build-dependencies]

[profile.release]
lto = true
