[package]
name = "texlab-components"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
once_cell = "1.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
texlab-protocol = { path = "../texlab_protocol" }
