[package]
name = "texlab-protocol"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
async-trait = "0.1"
bytes = "0.5"
futures = "0.3"
jsonrpc = { path = "../jsonrpc" }
jsonrpc-derive = { path = "../jsonrpc_derive" }
log = "0.4"
lsp-types = "0.74.0"
nom = "5.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1"
tokio-util = { version = "0.3", features = ["codec"] }
url = "2.1"
