[package]
name = "texlab-syntax"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
itertools = "0.8"
once_cell = "1.3"
petgraph = { version = "0.5", features = ["serde-1"] }
rayon = "1.3"
smallvec = "1.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
tempfile = "3.1"
texlab-protocol = { path = "../texlab_protocol" }
texlab-tex = { path = "../texlab_tex" }
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
indoc = "0.3"
