[package]
name = "texlab-tex"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
byteorder = "1.3"
futures = "0.3"
futures-boxed = { path = "../futures_boxed" }
tempfile = "3.1"
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }
