[package]
name = "bibutils-sys"
version = "0.1.0"
authors = [
    "Eric Förster <eric.foerster@outlook.com>", 
    "Patrick Förster <patrick.foerster@outlook.de>"]
edition = "2018"

[lib]
doctest = false

[build-dependencies]
cc = "1.0"
