[package]
name = "texlab-feature"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
async-trait = "0.1"
futures = "0.3"
itertools = "0.9"
log = "0.4"
petgraph = { version = "0.5", features = ["serde-1"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
texlab-components = { path = "../texlab_components" }
texlab-protocol = { path = "../texlab_protocol" }
texlab-syntax = { path = "../texlab_syntax" }
texlab-tex = { path = "../texlab_tex" }
titlecase = "1.1"
tokio = { version = "0.2", features = ["full"] }
