[package]
name = "texlab-hover"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
async-trait = "0.1"
base64 = "0.12"
futures = "0.3"
image = "0.23"
itertools = "0.9"
log = "0.4"
once_cell = "1.3"
petgraph = { version = "0.5", features = ["serde-1"] }
regex = "1.3"
tempfile = "3.1"
texlab-citeproc = { path = "../texlab_citeproc" }
texlab-components = { path = "../texlab_components" }
texlab-feature = { path = "../texlab_feature" }
texlab-protocol = { path = "../texlab_protocol" }
texlab-syntax = { path = "../texlab_syntax" }
texlab-tex = { path = "../texlab_tex" }
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
indoc = "0.3"
