name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run tests
        with:
          command: test
          args: --locked
  build_freebsd:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rustup
        with:
          run: |
            curl https://sh.rustup.rs -sSf | sh
            rustup default stable
      - name: Run tests
        with:
          run: |
            cargo test --locked
